# Generated by Django 2.2.1 on 2019-05-29 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='data_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
